### ISSUE TITLE
Sphinx Documentation online

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#163]
# Issue
Right now the documentation has a workflow that requires editing source files, converting them to PDF, then uploading them to a server. This requires a middleman with that kind of access, of which could cause a bottleneck sometimes. It also discourages editing documentation directly as it's a slower process to see updates.

Also, editing *.odt files can't be done on Github or very collaboratively (no more than 1 person per document at a time) - and they require third party software to edit them. 

Also, the PDF documents need to be routinely indexed and verified with search engines to be updated - making search results a little tricky with SEO and the PDF files quickly become outdated (dead links, bad search results). 

# Solution
Godot, another open source software has used Sphinx, similar to Blender, with the added link to a Github repository - hosting on Github. 

![firefox_2020-01-15_11-27-29](https://user-images.githubusercontent.com/35357409/72452053-e4b05f80-378a-11ea-9de3-113770aba95b.png)

## Benefits
These are some of the benefits when we move documentation online:
- Search engine indexing would be automatic for bots to update.
- files can be worked on by multiple people at the same time (in theory)
- design formatting is more consistent
- link to Github tasks and integration would be better and more at hand
- workflow wouldn't need to use PDF conversion to publish to a server

# Current Status
@cyberfoxhax in the official Discord chat has gone ahead and converted the entire collection of the documentation for Bforartists 2 into Sphinx, ready to commit. He created a custom script to convert the *.ODT files to Sphinx with good results. 

![unknown(1)](https://user-images.githubusercontent.com/35357409/72452627-e29ad080-378b-11ea-9180-8b646afdab69.png)
![unknown(2)](https://user-images.githubusercontent.com/35357409/72452629-e3cbfd80-378b-11ea-8a42-756057410365.png)
![unknown](https://user-images.githubusercontent.com/35357409/72452633-e4fd2a80-378b-11ea-9751-a16ddd1faa89.png)

# Task
1. Create a branch
2. Commit the Sphinx architecture and documentation to the repository (~100mb w/images)
3. Review the new documentation
4. Host the new documentation online and test
5. Update links and wiki in the official location/links
6. Connect this Github tracker to the documentation for quick edits and better collaboration when directly in the documentation online
7. Test editing workflow

This process requires some investigation and collaboration to implement, but a lot of the conversion work is already done and this Sphinx wiki repo could be hosted directly with Github. 

https://pages.github.com/
https://www.docslikecode.com/articles/github-pages-python-sphinx/

Here are some pro's and method of how Shinx and Github symbiosis can work (to have a good quality check pull request workflow with tracker and documentation editing)
https://github.com/godotengine/godot-docs

**Comment by ReinerBforartists** [comment]
Sphinx? WOAH! Never! I will not install this crap at my server ! Sorry :D

The idea to have a online documentation where everybody can change everything is nice. But it does not work this way. Sphinx is exactly the bottleneck at the Blender documentation. Sphinx requires you to be a programmer to write the manual. Crazy. ODT files can be edited by everybody. And you still need somebody to maintain the uploads. So we win exactly nothing, but loose everyting. Like full text search. Try to find anything in the Blender manual.

So please, nooooooo !!!

Won't do this, sorry :)

**Comment by ReinerBforartists** [comment]
Wrong button again. Didn't want to close this issue immediately. We can still discuss about everything. But really, Sphinx is the worst solution that you can choose.

**Comment by Draise14** [comment]
> Like full text search. Try to find anything in the Blender manual.
Full text search is with CTRL+F in any webpage. It's the same in a PDF documents (open chapter, search term, highlight results) - I don't know what is superior searching for info in a PDF is? Sphinx also has an indexed dedicated search box and results which works the same as other site-wide search systems on other websites. Google/Duckduckgo also indexes Sphinx better than a PDF. I've tried searching in BFA documentation online, and links and results are sometimes outdated and broken. Apparently search bots don't index PDF files so often.

How is searching within and for individual PDF files or an index any better? 

> And you still need somebody to maintain the uploads. 
Yeah.. it does look like it has a different set of steps to get it going, some can be automated, others not. And yeah.. markup or it's system is.. not as straight forward. 

I suppose this looked attractive as I'm just used to reading manuals in PDF form since the early 2000's. Surely there must be something better out there, and a responsive website online does feel nicer than PDF. 

Ideally another user friendly wiki service that is online would be great... one that is easily navigable, has a dedicated index/search system and doesn't need any third party files to update with easy collaboration and direct editing systems that work with a WYSIWYG editor. No third party software needed, no updating files on a server, no exporting design and format, no design inconsistencies. Even could have a modern system with content widgets, animations, and other web-page benefits for aiding in learning, like in browser video player, supporting files, etc.... A simple design that is responsive and that can be read on the phone even. A PDF can't be read easily on a phone and embedding videos is impossible. 

Something like [Webflow](https://webflow.com/) design/document capabilities or something like [Bit.ai](https://bit.ai/). These are all paid, and there is not much else out there that is opensourced and great for collaboration other than.. a simple Github Wiki or continue with PDF documentation? 

Sigh.. there must be some other way user friendly way that dynamic and sleak.

**Comment by Draise14** [comment]
I guess my only key arguement for Sphinx is that... the *.odt files are generated to Sphinx files through script, so editing the original PDF fiels could remain the same, just it's also published to the responsive sphinx site hosted on Github Pages.

**Comment by Draise14** [comment]
If it were with Docsify, it would make Github type editing of Markup pretty straight forward and collaborative, and still load a sleek and fast documentation site with a good search index system.

**Comment by ReinerBforartists** [comment]
>Full text search is with CTRL+F in any webpage. 

It searches just the current page loaded. And a Sphinx document is made of several pages. I rememer that it was around 1200 for the Blender manual. And this counts for all the other systems out there. From Doxygen to Docsify. They all suffer from the search problem.

I will definitely not give up the PDF version. Too much benefits compared to the Sphinx version. So the question is if somebody is willing to do the extra work for Sphinx, since i won't do it. And the question is if it does not confuse the user to have two systems.

**Comment by Draise14** [comment]
Yeah, it is on current page.. but.. ah... huh? The search index systems of both Sphinx and Docsify searches the entire website and give results according to the entire site index. With PDF, I can't search accros multiple documents natively. 

How do I do that?

**Comment by ReinerBforartists** [comment]
Well. Grab any menu in Blender, and search in the Sphinx Blender manual for the first ten operators in the menu. Count how often you will find the operator as the first hit in the list. Then count how often you will find the operator in the search results at all. 

My results is always 99% to not find anything useful. And when the search term is more than one word then you have completely lost anyways. I use Google when i want to find something in the Blender manual. The search in the Sphinx manual system is simply not reliable.

Sphinx was one of the first things that i evaluated when i started the fork since it is what the Blender devs uses natively. And it would have been the fastest method. Simply grab the Blender manual and replace everything Blender by Bforartists. But i quickly decided to skip this system then for given reasons. It is not good, it is a nightmare for users. And you can't have it offline. You have seen my first happy reaction when you mentioned that you want this system back :D

> With PDF, I can't search accros multiple documents natively.

We have the complete PDF as one big file. This means full text search across everything. 

We have of course the single chapters too. Which allows more fine control. When you search for a tool in the 3D view then it's most likely in one of the chapters in the 3D view. That's where the sub chapter system with the breadcrumbs comes in handy. It allows you to find the menu item in the manual, and allows you to find an operator from the manual in the UI.

For example, you are in the 3D view. Let's open the View menu. Now for example, we want to find out what clipping border in the 3D view does. 3D View is chapter 7 Editors - 3D View. Header is chapters 7.1 Editors - 3D View - Header. And the View menu is in chapter 7.1 Editors - 3D View - Header - View Menu . And you can still search the whole document with full text search. This works also in reverse direction, coming from the manual. And you are able to find everything anytime even with the single chapters.

This works of course just when the tools are really in the tools area and the options are really in the options area and so on. And when the manual structure fits. This does not work with the Blender manual where you have several chapters for the same thing across the whole manual, and  no real useful structure.

Well, we do have a better manual structure. The above method would work with our Sphinx version too. So it would be worth a shot. But we would still suffer from the unreliable search in Sphinx. Do the same test as mentioned above. Grab one menu of your choice, and try to find the first ten operators with the Sphinx search.

**Comment by ReinerBforartists** [comment]
By the way, the content of the repository is work in progress, and contains lots of unfinished chapters that we haven't touched yet, plus the old chapters that will vanish in nearer future. So before converting the whole content to Sphinx you would have to sort that bits out. And this with every update. So it would make sense to wait with a Sphinx system until we are at least through with converting the old manual parts. That's currently over 40 still open issues in the tracker.

The somehow finished chapters are the single pdf files that you can find at the webpage.

**Comment by ReinerBforartists** [comment]
My biggest fear is that you start something here that i have to maintain then. And as told, i am not a happy bunny with Sphinx. I would delete it in the moment i would have to work with it.

Let's make a deal. You can have a look how far you can really push it as long as i can keep my fingers out of it as much as possible. When that's the case, then you have green light :)

I would be curious to know if and how you can really host the Sphinx manual at Github.

**Comment by Draise14** [comment]
Sounds alright, trying to prototype it. Makes sense. Yeah.. I don't really want to put more work on you, only trying to find good solutions that others could work on. 

I do agree with you, the manual is not downloadable and available offline with Sphinx only, which should be an option. Having download links of the chapters in Sphinx would be a beautiful symbiosis. 

And yes, I do agree, the chapter structure is much better than Blenders. 

And yes, I do agree.. searching for terms the entire documentation wide area would be.... like seeing 100 word results for a term you want. PDF or not, google SEO and indexing would help. 

Anyway, thanks for the open mind. We'll give it a go to host on Github and see how much work it is to maintain - I think the workflow from converting from ODT to Sphinx then to also get the PDF's can be tested well enough. 

The only issue with the script conversion so far is converting the hotkey table chapters.

**Comment by ReinerBforartists** [comment]
Hey friends, 

Totally overlooked this task here. We have the Bforartists manual for version 2.50 ready. So you could create a first sphinx version now if you want :)

https://github.com/Bforartists/Manual/releases/tag/v2.5.0

**Comment by Draise14** [comment]
Cool. I'll take a look and ask @CyberFoxHax on the next steps.

**Comment by ReinerBforartists** [comment]
Any news here?

**Comment by Draise14** [comment]
Apparently Cyberfox, who made the script, is awol at the moment due to a number of life things the past year, meaning I am actually not sure how to run it correctly. I didn't get a chance to write down the instructions so.. eh... I guess we don't need the spinx documentation for now. Let's close for now.

**Comment by ReinerBforartists** [comment]
Okay :)
