### ISSUE TITLE
Suggestion: The manual looks flat: Add depth to it!

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#225]
All the chapters in the manual appear in a continuous sequence. 
This flat structure of the manual makes it look unprofessional, and also makes it less readable.

(In fact, people expect to see standard parts of a manual, like an attractive cover, a TOC, preface, etc. Without these parts, it looks like a home-brewed document.)

Also, if we increase the _depth_ of the manual, it will become more readable with the same content.
(We need to tweak the hierarchy and layout of the manual.)

**Suggested steps:**
1.  Divide the manual into logical Parts. Each part begins with a blank page with a title in bold large font.
2.  The parts could be <br> **1. General**: Contains the preface, TOC, introduction, how to use the manual, <br> **2. About Blender:** General description of Blender, types of controls, etc. <br> **3. All about Editors:** (actual functionality of Blender) <br> **4. Glossary:** terms and concepts <br> **5. The change notes:** This is like the traditional _Release notes_, but describes the departure from Blender only. Include screenshots with numbers as annotations. Below the screenshot, each number explains how that particular change benefits the users. 

The last section may look trivial, but this is the part that experienced Blender users will want to check out. The more convincing it becomes, the more people you can wean away from Blender. Plus it serves as a basis for any enthusiastic user to make YouTube videos. (Many more people will be willing to watch a YouTube video as compared to reading a change notes.

Since bforeartists is always going to be "an improved Blender", we may as well exploit the vast resources of Blender. Thus if the user is told how exactly b4a differs from Blender, he can always watch the Blender videos and books, and then use b4a without much difficulty. (Without these change notes, he has to struggle to reconcile the differences between the two GUIs, and that is highly irritating.)

BTW if the changed GUI leads to a major change in his workflow, then b4a manual must have a dedicated chapter that explains how the workflow is simplified. Most users will NOT bother to work out this advantage!

**Comment by raindropsfromsky** [comment]
BTW note that when we divide the manual in parts, our chapters in each part can be proposed to the top hierarchy, rather than being at 3rd position in the breadcrumbs!

And yet we can use the outline trick to show the topic in its proper depth.

For example, your current breadcrumb looks like this:

Chapter number - Editor type - Editor area - Tab and panel if available - Object type - and the mode 

Instead of that, split the content as follows:
Part = Editor type (a whole blank page)
Section = Editor area (a blank page, with a screenshot of the editor in the bottom half)
Chapter = tabs (H1), panels (H2), objects (H3), modes (H4).

**Comment by ReinerBforartists** [comment]
Thanks for the thoughts. I am a bit lost with your requests here though. Better make one issue for one thought. Or we end in discussing everything about everything. Like before. And the good ideas then sinks in the discussion. This is not productive.

Shortening the breadcrumbs imho just leads to destroying the breadcrumbs. I think we discussed this already. You want short names, i need long names to have the breadcrumbs system working. So i have to deny this idea, sorry.

In general this sounds like a complete rewrite, in favour of something that we discussed already. The manual is no tutorial. It is the reference manual. It explains the tools. Not the workflows. But what you request is exactly that. Tutorials to teach the Blender user how to use Bforartists. Tutorials of how to use the manual. General CG tutorials. Editor turorials. And Workflow tutorials. On top of this you request us to write complete chapters where we differ from Blender.

I know that we fundamentally differ in the meaning of a manual. This all does in my opinion simply not belong to our manual, sorry. And so i will always veto such thoughts. We are Bforartists, not Blender. We don't teach the people how to use Blender. We teach them how to use Bforartists. And this is done in tutorials. Not in the manual.

A car manual does not teach you the traffic rules. It also does not explain what a windshield wiper is good for. It explains how you turn on or off the windshield wipers. And what to do when the wiper doesn't work proper anymore. The technical part. That's what a reference manual is good for.

I would create more tutorials. But i have no good experience with our tutorial series. We have thousands of downloads every month. But our official learning videos are just watched a few dozen times since we have it online. And nobody requests tutorials. There is no demand. So i spend my time at the code instead nowadays. We are short of manpower. So i have to set priorities.

**Comment by ReinerBforartists** [comment]
Some thoughts, and to separate two of your requests:

Adding a front page image for each chapter would add 400 pages since we have 400 chapters ...

And regarding the intro chapter i think you mean something like the first page of the Blender manual? We can't link to the chapters though. They are in permanent change. This would be a maintaining nightmare.

**Comment by raindropsfromsky** [comment]
No, I means extra pages for only the parts (which would mean 5 pages extra).

We need just one cover page, for the whole manual (not for each chapter).
Every book in the market has an attractive cover. B4A manual does not have a cover page at all.

**Comment by ReinerBforartists** [comment]
Okay :)

I'll make it a task.

**Comment by ReinerBforartists** [comment]
Still lost with the term depth.

> Divide the manual into logical Parts. Each part begins with a blank page with a title in bold large font.

This would add 400 pages to the manual. We need an easier way here. One that does not blow up the manual. Maybe make the table of content colored? But then the table of content becomes hard to read.

**Comment by ReinerBforartists** [comment]
Some header experiments for the single chapters. That's just 400 tables, and not 400 new pages ...

![headers](https://user-images.githubusercontent.com/13919702/107765957-05067100-6d33-11eb-9a1a-7848b23e5997.jpg)

**Comment by ReinerBforartists** [comment]
Let's use number one. Clean, simple. It will take a while though to add this to all chapters ...

**Comment by ReinerBforartists** [comment]
Separating the task, and closing this issue. All in one issues are not good. Please make separated tasks in case you have more ideas. But i think we have picked the for us useful ones now.
