### ISSUE TITLE
Geometry Nodes - Named Attribute Nodes needs to be added

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#266]
Add the named attribute to the documentation

[Linked Task](https://github.com/Bforartists/Bforartists/issues/2986)

**Comment by ReinerBforartists** [comment]
As a note, you can of course make a tracker entry for every update in the manual. But i usually do all changes at the manual for the current merge in one big commit. After i went through the list of commits. And after i have fixed the tracker entries for the merge.

I usually then commit it to the "update the manual" thread. Like this one: https://github.com/Bforartists/Manual/issues/260

This keeps the number of changed files small. Since it can be that you touch one chapter more than once. And the odt files for the manual are not pure text files that can be merged. Means with every commit you add a new document to the history. There is a reason that the repo is so big ...

**Comment by Draise14** [comment]
Ah ok. I can do one commit to save there and tag all the relevant tasks in the same commit. I think I will need to be granular with this process in the tracker since I won't be able to keep it all in my head with all the other work I have to do for clients on the daily also. 

Concerning internet bandwidth, it's alright for now, but I'll try keep the commits to a minumum. Maybe once a week.

**Comment by ReinerBforartists** [comment]
It's not about the bandwidth. It's about blowing up the repository :)

**Comment by ReinerBforartists** [comment]
Pic or it didn't happen!

**Comment by ReinerBforartists** [comment]
Fixed
