### ISSUE TITLE
3D View - Transform mode "Snap Base" 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#447]
> This commit implements a new modifier key (`B`) for the transform
> operators.
> 
> This new key allows changing the 'Snap Base' of a transform by snapping
> it to a defined point in the scene.

Relevant Bforartists Task
[https://github.com/Bforartists/Bforartists/issues/3572](https://github.com/Bforartists/Bforartists/issues/3572)

<details>
<summary>Blender Task</summary>

SHA-1: 3010f1233b299be61f732acf1ea7aaa4b70017be

* Transform: new feature to edit the 'Snap Base'

This commit implements a new modifier key (`B`) for the transform
operators.

This new key allows changing the 'Snap Base' of a transform by snapping
it to a defined point in the scene.

Ref #66424

# Implementation Details

- This feature is only available in the 3D View.
- This feature is only available for the transform modes:
  - `Move`,
  - `Rotate`,
  - `Scale`,
  - `Vert Slide` and
  - `Edge Slide`.
- The `Snap Base Edit` is enabled while we are transforming and we
  press the key `B`
- The `Snap Base Edit` is confirmed when we press any of the keys:
 `B`, `LMB`, `Enter`
- During um operation, if no snap target is set for an element in the
  scene (Vertex, Edge...), the snap targets to geometry Vertex, Edge,
  Face, Center of Edge and Perpendicular of Edge are set automatically.
- Constraint or similar modal features are not available during the
  `Snap Base Edit` mode.
- Text input is not available during the `Snap Base Edit` mode.
- A prone snap base point is indicated with an small cursor drawing.

Pull Request: https://projects.blender.org/blender/blender/pulls/104443

</details>

**Comment by ReinerBforartists** [comment]
Needs a fix of the hotkey conflict first.

https://github.com/Bforartists/Bforartists/issues/3619

**Comment by ReinerBforartists** [comment]
I miss something here. B just snaps the object back to its initial position all the time. Not sure if i do something wrong.

**Comment by ReinerBforartists** [comment]
Ah now i see how it is meant to work. Usualyl the center of the object is the snap base. But with this tool you can set the snap base to another point, at the corner of another object in the scene for example.

![snapbase1](https://github.com/Bforartists/Manual/assets/13919702/03d725f9-3bf0-4252-b57f-3519c2c9e311)

The bigger problem is, we don't have the modal tools that are shown at the bottom documented at all. Nowhere in the whole manual. This would be a monster task to catch them and document them all. Since so far it was self explaining functionality like limiting to x axis and stuff. This here is something different though.

Shall we really? And how?

![notdocumentedyet](https://github.com/Bforartists/Manual/assets/13919702/8b18948a-8c58-4ccb-8c4d-c6527900888c)

**Comment by ReinerBforartists** [comment]
Ah doesn't help. I'll have a look how to do this.

**Comment by ReinerBforartists** [comment]
Good news is, modal operators are the same for all transform tools. So just one entry. KK.

**Comment by ReinerBforartists** [comment]
The bad news is, if we really do this then we need to do it for the other +1200 tools too -.-

**Comment by ReinerBforartists** [comment]
Sheesh, alone for the transform tools you get mad with the different modes ...

**Comment by ReinerBforartists** [comment]
At least fixed for the transform tools now
