### ISSUE TITLE
Exporter - GLTF has an option to export Vertex Color attributes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#623]
![image](https://github.com/Bforartists/Manual/assets/35357409/a1d5a652-0e26-4577-a5fc-6e46cf18d906)

Related task:
#603

<details>
<summary>Details</summary>

SHA-1: 0f0a8df8a922cdb0796c0b3fdbdc5c669efb3059

* glTF exporter: Option to export VC even if not used in node tree

glTF specification says that VC must be used as a base color multiplier, so you should add it to your node tree to see it.
But seems common usage of VC is to use it for custom data. Custom properties/attribute is the best place for these data,
but in order not to break production workflow/pipeline, we add an option to export active VC

</details>

**Comment by ReinerBforartists** [comment]
Whole gltf chapter is outdated

**Comment by ReinerBforartists** [comment]
As usual, it is not one new option, but the whole thing is completely outdated. And holy molly, how much options can one put into a single exporter ....

**Comment by Draise14** [comment]
Yeah refactoring these. Will commit after the merge.

**Comment by Draise14** [comment]
Merge conflict. I too have already done it.

**Comment by ReinerBforartists** [comment]
Okay, i will trash my work then.

Draise, for the future, please respect assignments. When you want to fix the task, then assign. When somebody is already assigned, let him do the task. That's the whole idea behind the tracker.

I have now worked three hours for the birds. That's not how it should be. And that's why we have the system of assigning to a task. Assignee is the one who fixes it then. When you want take over, then please first ask.

**Comment by Draise14** [comment]
I did.
#603

**Comment by ReinerBforartists** [comment]
I see. Then you would have to close this one, since this was the manual task.

**Comment by ReinerBforartists** [comment]
I will close it as double now if you don't mind
